-- MySQL Script generated by MySQL Workbench
-- Mon Jun 23 13:43:50 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema phanes
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `phanes` ;

-- -----------------------------------------------------
-- Schema phanes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `phanes` DEFAULT CHARACTER SET utf8 ;
USE `phanes` ;

-- -----------------------------------------------------
-- Table `phanes`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phanes`.`users` (
  `user_id` BIGINT NOT NULL,
  `nickname` VARCHAR(10) NOT NULL,
  `profil_img` VARCHAR(500) NOT NULL,
  `nick_updated_period` TIMESTAMP NULL DEFAULT NULL,
  `create_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `platform` ENUM('kakao', 'google') NOT NULL,
  `platform_key` VARCHAR(100) NOT NULL,
  `status` ENUM('d', 'b', 'u', 'a') NOT NULL DEFAULT 'u',
  `last_login` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `browser` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `phanes`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phanes`.`projects` (
  `project_id` BIGINT NOT NULL AUTO_INCREMENT,
  `project_name` VARCHAR(45) NOT NULL,
  `creator_id` BIGINT NOT NULL,
  `url` VARCHAR(100) NOT NULL,
  `language` ENUM('j', 'js', 'py', 'c', 'cp') NOT NULL DEFAULT 'j',
  `description` VARCHAR(255) NULL DEFAULT 'null',
  PRIMARY KEY (`project_id`),
  INDEX `fk_projects_users_idx` (`creator_id` ASC) VISIBLE,
  CONSTRAINT `fk_projects_users`
    FOREIGN KEY (`creator_id`)
    REFERENCES `phanes`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `phanes`.`project_member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phanes`.`project_member` (
  `project_id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  `members_id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` CHAR(1) NOT NULL,
  INDEX `fk_project_member_projects1_idx` (`project_id` ASC) VISIBLE,
  INDEX `fk_project_member_users1_idx` (`user_id` ASC) VISIBLE,
  PRIMARY KEY (`members_id`),
  CONSTRAINT `fk_project_member_projects1`
    FOREIGN KEY (`project_id`)
    REFERENCES `phanes`.`projects` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_project_member_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `phanes`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `phanes`.`chats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phanes`.`chats` (
  `chats_id` BIGINT NOT NULL AUTO_INCREMENT,
  `project_id` BIGINT NOT NULL,
  `project_members_id` BIGINT NOT NULL,
  `sent_at` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `messages` TEXT NOT NULL,
  PRIMARY KEY (`chats_id`),
  INDEX `fk_chats_projects1_idx` (`project_id` ASC) VISIBLE,
  INDEX `fk_chats_project_member1_idx` (`project_members_id` ASC) VISIBLE,
  CONSTRAINT `fk_chats_projects1`
    FOREIGN KEY (`project_id`)
    REFERENCES `phanes`.`projects` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chats_project_member1`
    FOREIGN KEY (`project_members_id`)
    REFERENCES `phanes`.`project_member` (`members_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `phanes`.`project_files`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phanes`.`project_files` (
  `project_id` BIGINT NOT NULL,
  `file_path` VARCHAR(255) NOT NULL,
  `file_name` VARCHAR(255) NOT NULL,
  `file_created_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `file_type` ENUM('j', 'js', 'py', 'c', 'cp') NOT NULL,
  `saved_time_at` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `file_created_user_id` BIGINT NOT NULL,
  INDEX `fk_project_files_projects1_idx` (`project_id` ASC) VISIBLE,
  UNIQUE INDEX `file_path_UNIQUE` (`file_path` ASC) VISIBLE,
  INDEX `fk_project_files_users1_idx` (`file_created_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_project_files_projects1`
    FOREIGN KEY (`project_id`)
    REFERENCES `phanes`.`projects` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_project_files_users1`
    FOREIGN KEY (`file_created_user_id`)
    REFERENCES `phanes`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
